Stat svc
vladbakushkin/java-explore-with-me pull request #1
Opened 2024-07-02 19:59 UTC by vladbakushkin

1. Реализован сервис статистики в соответствии со спецификацией: [ewm-stats-service.json](https://raw.githubusercontent.com/yandex-praktikum/java-explore-with-me/main/ewm-stats-service-spec.json).
2. Реализован HTTP-клиент для работы с сервисом статистики.
3. Подготовлена сборка проекта.

2024-07-03 15:39 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара мелких замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-03 15:39 UTC, LexLippi commented on stats-service/stats-client/src/main/java/ru/practicum/ewm/statsservice/statsclient/StatsClient.java
> +                "uris", uris == null ? "" : uris,
Не очень понятно зачем маппить `null` в пустую строчку. Если проблема с тем, что `Map` не поддерживает `null`, то существуют специальные виды `Map`, которые поддерживают `null` в качестве значения

2024-07-03 15:39 UTC, LexLippi commented on stats-service/stats-dto/src/main/java/ru/practicum/ewm/statsservice/statsdto/HitDto.java
> +@ToString
Может использовать аннотацию `@Data`?
Она в себе все эти содержит

2024-07-03 15:39 UTC, LexLippi commented on stats-service/stats-dto/src/main/java/ru/practicum/ewm/statsservice/statsdto/StatsDto.java
> +@ToString
Аналогично про `@Data`

2024-07-03 15:39 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/statsservice/statsserver/model/Stats.java
> +@ToString
Аналогично про `@Data`

2024-07-03 17:24 UTC, vladbakushkin commented on stats-service/stats-dto/src/main/java/ru/practicum/ewm/statsservice/statsdto/HitDto.java
> +@ToString
Действительно, заменил на `@Data`

2024-07-03 17:24 UTC, vladbakushkin commented on stats-service/stats-dto/src/main/java/ru/practicum/ewm/statsservice/statsdto/StatsDto.java
> +@ToString
Заменил на `@Data`

2024-07-03 17:24 UTC, vladbakushkin commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/statsservice/statsserver/model/Stats.java
> +@ToString
Заменил на `@Data`

2024-07-03 17:59 UTC, vladbakushkin commented on stats-service/stats-client/src/main/java/ru/practicum/ewm/statsservice/statsclient/StatsClient.java
> +                "uris", uris == null ? "" : uris,
Т.к. на стороне сервера обрабатывается и `null` и пустой список, то это был самый простой способ обойти ограничение `null` в качестве значения.
Заменил на `HashMap`, которая это поддерживает.

2024-07-04 07:04 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи со следующими этапами диплома!

2024-07-04 17:20 UTC, merged