Main svc
vladbakushkin/java-explore-with-me pull request #2
Opened 2024-07-18 19:24 UTC by vladbakushkin

Реализован основной сервис приложения

2024-07-19 17:51 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара мелких замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-19 17:51 UTC, LexLippi commented on main-service/src/test/java/ru/practicum/ewm/mainservice/category/controller/CategoryAdminControllerTest.java
> +    }
Зачем здесь два пустых теста?

Если хотим проверить поднятие контекста, то одного достаточно, иначе непонятно

2024-07-19 17:51 UTC, LexLippi commented on main-service/src/test/java/ru/practicum/ewm/mainservice/category/controller/CategoryAdminControllerTest.java
> +//    }
Почему эта часть тестов закомментирована?

2024-07-19 18:09 UTC, vladbakushkin commented on main-service/src/test/java/ru/practicum/ewm/mainservice/category/controller/CategoryAdminControllerTest.java
> +//    }
Хотел сначала попробовать написать тесты через swagger, но потом понял, что не хватает времени :( и забыл удалить

2024-07-19 18:10 UTC, vladbakushkin commented on main-service/src/test/java/ru/practicum/ewm/mainservice/category/controller/CategoryAdminControllerTest.java
> +    }
Удалил пустые тесты

2024-07-20 07:42 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с заключительным этапом диплома!

2024-07-20 08:36 UTC, merged